<?php

namespace BazookasBundle\Repository;

/**
 * CollectionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionItemRepository extends \Doctrine\ORM\EntityRepository
{
}
